### PR TITLE
Lint BlazarUI

### PR DESCRIPTION
**Pull request by zdhickman**
@andyhuang91 This PR sets up standard eslint rules, automatically fixes what we can with `--fix`, and fixes scripts in every folder besides `/components`

cc @gchomatas

### CODE REVIEW

**Comment by zdhickman** [comment]
All linting errors should be fixed now. There are only linting warnings for `console.warn`s

**Comment by Calvinp** [comment]
You can disable those on a line-by-line basis when you actually want a console warning:
http://eslint.org/docs/user-guide/configuring.html#disabling-rules-with-inline-comments

**Comment by andyhuang91** [comment]
I'm going to say that I trust you but you should probably wait until Monday to release it so that you can quickly fix any problems that people notice.

**Comment by zdhickman** [comment]
I'm going to merge this into `beta` and deploy and wait a few days to see if any hidden bugs come up.

**Pull request merged**
