### PR TITLE
Reset cache

### PR DESCRIPTION
**Pull request by zdhickman**
screen shot 2016-04-12 at 11 30 54 am

What kind of copy do we want here? How much info/what wording? @markhazlewood @jhaber @jonathanwgoodwin @gchomatas 

Adding copy for the downstream modules tooltip as well

### CODE REVIEW

**Comment by jonathanwgoodwin** [comment]
It would be _really_ cool to show what directories were cached last time.
That also nicely covers the case where most HubSpot users don't actually have a use for this feature.

**Comment by also** [comment]
The current copy ("Clear cached directories set in blazar.yaml") is misleading–the cached directories for most builds would come from a buildpack, not a module `.blazar.yaml`.

**Comment by also** [comment]
Oh also, "blazar.yaml" vs. ".blazar.yaml"

**Comment by zdhickman** [comment]
Yep, you might as well replace what I currently have in the tooltip with lorem ipsum

**Comment by jhaber** [comment]
Showing the previous cached directories would be cool but not necessary accurate if the buildpack has changed since the last build

**Comment by zdhickman** [comment]
Okay, maybe we can stick with some succinct copy for now, and add more detail as necessary. Open to suggestions

**Pull request merged**
